"use client";
import { useState, useEffect, useCallback } from "react";
import { MessageSquare, Send, Trash2, Loader2, ThumbsUp, CornerDownRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent } from "@/components/ui/card";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
interface CU { name: string | null; image: string | null; }
interface CI { id: string; content: string; upvotes: number; isPinned: boolean; createdAt: string; userId: string; user: CU; replies?: CI[]; }
export function CommentSection({ entity, entityId, isLoggedIn }: { entity: string; entityId: string; isLoggedIn: boolean }) {
  const [comments, setComments] = useState<CI[]>([]); const [loading, setLoading] = useState(true);
  const [content, setContent] = useState(""); const [submitting, setSubmitting] = useState(false);
  const [replyTo, setReplyTo] = useState<string | null>(null); const [replyContent, setReplyContent] = useState("");
  const [upvoted, setUpvoted] = useState<Set<string>>(new Set());
  const load = useCallback(async () => { try { const r = await fetch(`/api/comments?entity=${entity}&entityId=${entityId}`); if (r.ok) { const d = await r.json(); setComments(d.comments); } } catch {} finally { setLoading(false); } }, [entity, entityId]);
  useEffect(() => { load(); }, [load]);
  const submit = async () => { if (!content.trim()) return; setSubmitting(true); try { const r = await fetch("/api/comments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entity, entityId, content: content.trim() }) }); if (!r.ok) { const d = await r.json(); throw new Error(d.error); } const d = await r.json(); setComments(p => [{ ...d.comment, replies: [] }, ...p]); setContent(""); toast.success("Posted!"); } catch (e) { toast.error(e instanceof Error ? e.message : "Failed"); } finally { setSubmitting(false); } };
  const submitReply = async (pid: string) => { if (!replyContent.trim()) return; try { const r = await fetch("/api/comments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entity, entityId, content: replyContent.trim(), parentId: pid }) }); if (!r.ok) throw new Error(); const d = await r.json(); setComments(p => p.map(c => c.id === pid ? { ...c, replies: [...(c.replies ?? []), d.comment] } : c)); setReplyTo(null); setReplyContent(""); toast.success("Reply posted!"); } catch { toast.error("Failed"); } };
  const del = async (id: string) => { if (!confirm("Delete?")) return; try { await fetch(`/api/comments?id=${id}`, { method: "DELETE" }); setComments(p => p.filter(c => c.id !== id)); toast.success("Deleted."); } catch { toast.error("Failed"); } };
  const upvote = async (id: string) => { if (upvoted.has(id)) { toast.info("Already upvoted."); return; } setUpvoted(p => new Set(p).add(id)); setComments(p => p.map(c => c.id === id ? { ...c, upvotes: c.upvotes + 1 } : c)); try { const r = await fetch(`/api/comments/${id}/upvote`, { method: "POST" }); if (!r.ok) { setComments(p => p.map(c => c.id === id ? { ...c, upvotes: c.upvotes - 1 } : c)); setUpvoted(p => { const n = new Set(p); n.delete(id); return n; }); if (r.status === 401) toast.error("Login to upvote."); } } catch { setComments(p => p.map(c => c.id === id ? { ...c, upvotes: c.upvotes - 1 } : c)); } };
  const fmt = (d: string) => { const diff = Date.now() - new Date(d).getTime(); if (diff < 60000) return "now"; if (diff < 3600000) return `${Math.floor(diff/60000)}m`; if (diff < 86400000) return `${Math.floor(diff/3600000)}h`; return new Date(d).toLocaleDateString(); };
  return (<div className="space-y-4">
    <div className="flex items-center gap-2"><MessageSquare className="h-4 w-4 text-primary" /><h3 className="text-base font-semibold">Discussion ({comments.length})</h3></div>
    {isLoggedIn ? <div className="space-y-2"><Textarea value={content} onChange={e => setContent(e.target.value)} placeholder="Share thoughts..." rows={3} maxLength={2000} /><div className="flex justify-between items-center"><span className="text-[10px] text-muted-foreground">{content.length}/2000</span><Button size="sm" onClick={submit} disabled={submitting || !content.trim()}>{submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <><Send className="h-3.5 w-3.5 mr-1" />Post</>}</Button></div></div> : <Card className="border-dashed"><CardContent className="py-4 text-center text-sm text-muted-foreground"><a href="/login" className="text-primary underline">Log in</a> to comment.</CardContent></Card>}
    {loading ? <div className="flex justify-center py-4"><Loader2 className="h-5 w-5 animate-spin text-muted-foreground" /></div> : comments.length === 0 ? <p className="text-sm text-muted-foreground text-center py-3">No comments yet. Start the discussion!</p> :
      <div className="space-y-3">{comments.map(c => (<div key={c.id} className="space-y-2">
        <Card><CardContent className="py-3"><div className="flex items-start gap-3"><Avatar className="h-7 w-7 shrink-0"><AvatarFallback className="text-[10px]">{(c.user.name ?? "U")[0].toUpperCase()}</AvatarFallback></Avatar><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="text-sm font-medium">{c.user.name ?? "Anonymous"}</span><span className="text-[10px] text-muted-foreground">{fmt(c.createdAt)}</span></div><p className="text-sm mt-1 whitespace-pre-wrap">{c.content}</p><div className="flex items-center gap-3 mt-2"><button onClick={() => upvote(c.id)} className={cn("flex items-center gap-1 text-xs", upvoted.has(c.id) ? "text-primary" : "text-muted-foreground hover:text-primary")}><ThumbsUp className="h-3.5 w-3.5" />{c.upvotes > 0 ? c.upvotes : ""}</button>{isLoggedIn && <button onClick={() => setReplyTo(replyTo === c.id ? null : c.id)} className="flex items-center gap-1 text-xs text-muted-foreground hover:text-primary"><CornerDownRight className="h-3.5 w-3.5" />Reply</button>}<button onClick={() => del(c.id)} className="text-xs text-muted-foreground hover:text-destructive"><Trash2 className="h-3.5 w-3.5" /></button></div></div></div></CardContent></Card>
        {replyTo === c.id && <div className="ml-10 space-y-2"><Textarea value={replyContent} onChange={e => setReplyContent(e.target.value)} placeholder="Reply..." rows={2} /><div className="flex gap-2"><Button size="sm" onClick={() => submitReply(c.id)} disabled={!replyContent.trim()}>Reply</Button><Button size="sm" variant="ghost" onClick={() => { setReplyTo(null); setReplyContent(""); }}>Cancel</Button></div></div>}
        {c.replies && c.replies.length > 0 && <div className="ml-10 space-y-2">{c.replies.map(r => <Card key={r.id} className="bg-muted/30"><CardContent className="py-2"><div className="flex items-start gap-2"><Avatar className="h-6 w-6 shrink-0"><AvatarFallback className="text-[10px]">{(r.user.name ?? "U")[0].toUpperCase()}</AvatarFallback></Avatar><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="text-xs font-medium">{r.user.name ?? "Anonymous"}</span><span className="text-[10px] text-muted-foreground">{fmt(r.createdAt)}</span></div><p className="text-sm mt-0.5">{r.content}</p></div></div></CardContent></Card>)}</div>}
      </div>))}</div>}
  </div>);
}
