"use client";
import { useState } from "react";
import { CheckCircle2, XCircle, Clock, FileText, HelpCircle, Loader2, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
export function CommunityAdmin({ guestPosts: gp, communityQuestions: cq }: { guestPosts: any[]; communityQuestions: any[] }) {
  const [posts,setPosts]=useState(gp); const [questions,setQuestions]=useState(cq); const [acting,setActing]=useState<string|null>(null);
  const reviewPost=async(id:string,action:string)=>{setActing(id);try{const r=await fetch("/api/admin/community/guest-posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})});if(!r.ok)throw new Error();setPosts(p=>p.map(x=>x.id===id?{...x,status:action==="publish"?"PUBLISHED":action==="approve"?"APPROVED":"REJECTED"}:x));toast.success(`${action}d`);}catch{toast.error("Failed");}finally{setActing(null);}};
  const reviewQ=async(id:string,action:string)=>{setActing(id);try{const r=await fetch("/api/admin/community/questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})});if(!r.ok)throw new Error();setQuestions(q=>q.map(x=>x.id===id?{...x,status:action==="reject"?"REJECTED":"APPROVED"}:x));toast.success(action==="import"?"Imported!":`${action}d`);}catch{toast.error("Failed");}finally{setActing(null);}};
  const badge=(s:string)=>s==="PENDING"?<Badge variant="outline" className="text-[10px] gap-0.5"><Clock className="h-2.5 w-2.5"/>Pending</Badge>:s==="APPROVED"||s==="PUBLISHED"?<Badge variant="secondary" className="text-[10px] gap-0.5 bg-emerald-100 text-emerald-700"><CheckCircle2 className="h-2.5 w-2.5"/>{s}</Badge>:<Badge variant="secondary" className="text-[10px] gap-0.5 bg-red-100 text-red-700"><XCircle className="h-2.5 w-2.5"/>Rejected</Badge>;
  const pp=posts.filter(p=>p.status==="PENDING"); const pq=questions.filter(q=>q.status==="PENDING");
  return<Tabs defaultValue="posts"><TabsList><TabsTrigger value="posts" className="gap-1 text-xs"><FileText className="h-3.5 w-3.5"/>Posts ({pp.length})</TabsTrigger><TabsTrigger value="questions" className="gap-1 text-xs"><HelpCircle className="h-3.5 w-3.5"/>Questions ({pq.length})</TabsTrigger></TabsList>
    <TabsContent value="posts" className="mt-4 space-y-3">{posts.length===0?<Card className="border-dashed"><CardContent className="py-6 text-center text-sm text-muted-foreground">No posts.</CardContent></Card>:posts.map(p=><Card key={p.id}><CardContent className="py-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex items-center gap-2 mb-1"><span className="font-medium text-sm">{p.title}</span>{badge(p.status)}</div><p className="text-xs text-muted-foreground">By {p.authorName} · {new Date(p.createdAt).toLocaleDateString()}</p>{p.excerpt&&<p className="text-xs text-muted-foreground mt-1 line-clamp-2">{p.excerpt}</p>}</div>{p.status==="PENDING"&&<div className="flex flex-col gap-1 shrink-0"><Button size="sm" variant="outline" onClick={()=>reviewPost(p.id,"approve")} disabled={acting===p.id}>Approve</Button><Button size="sm" onClick={()=>reviewPost(p.id,"publish")} disabled={acting===p.id}>Publish</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={()=>reviewPost(p.id,"reject")} disabled={acting===p.id}>Reject</Button></div>}</div></CardContent></Card>)}</TabsContent>
    <TabsContent value="questions" className="mt-4 space-y-3">{questions.length===0?<Card className="border-dashed"><CardContent className="py-6 text-center text-sm text-muted-foreground">No questions.</CardContent></Card>:questions.map(q=><Card key={q.id}><CardContent className="py-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex items-center gap-2 mb-1"><span className="font-medium text-sm">{q.question}</span>{badge(q.status)}</div><p className="text-xs text-muted-foreground">By {q.submitterName} · {q.exam?.title??q.category?.name??"General"}</p><div className="mt-2 grid grid-cols-2 gap-1 text-xs">{["A","B","C","D"].map((l,i)=><div key={l} className={cn("flex items-center gap-1 rounded p-1",q.correctAnswer===l?"bg-emerald-50 text-emerald-700 font-medium":"bg-muted")}><b>{l}.</b>{[q.optionA,q.optionB,q.optionC,q.optionD][i]}</div>)}</div></div>{q.status==="PENDING"&&<div className="flex flex-col gap-1 shrink-0"><Button size="sm" variant="outline" onClick={()=>reviewQ(q.id,"approve")} disabled={acting===q.id}>Approve</Button>{q.exam&&<Button size="sm" onClick={()=>reviewQ(q.id,"import")} disabled={acting===q.id}>{acting===q.id?<Loader2 className="h-3 w-3 animate-spin"/>:<><Upload className="h-3 w-3 mr-1"/>Import</>}</Button>}<Button size="sm" variant="ghost" className="text-destructive" onClick={()=>reviewQ(q.id,"reject")} disabled={acting===q.id}>Reject</Button></div>}</div></CardContent></Card>)}</TabsContent>
  </Tabs>;
}
