"use client";
import { useState } from "react";
import { CheckCircle2, XCircle, Clock, FileText, HelpCircle, Newspaper, Eye, Loader2, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
interface Stats { pendingGuestPosts:number;pendingQuestions:number;draftBlogPosts:number;unpublishedExams:number;unpublishedColleges:number;unpublishedBanks:number;unpublishedJobs:number;unpublishedGovtServices:number;totalReviews:number;totalComments:number; }
interface GPI { id:string;title:string;authorName:string;createdAt:string;excerpt:string; }
interface QI { id:string;question:string;optionA:string;optionB:string;optionC:string;optionD:string;correctAnswer:string;submitterName:string;createdAt:string;examTitle:string|null; }
interface DPI { id:string;title:string;authorName:string;updatedAt:string;categoryName:string|null; }
export function ReviewPanel({ stats, guestPosts, questions, draftPosts, unpublishedExams, unpublishedColleges }: { stats:Stats; guestPosts:GPI[]; questions:QI[]; draftPosts:DPI[]; unpublishedExams:any[]; unpublishedColleges:any[]; }) {
  const [acting,setActing]=useState<string|null>(null);
  const reviewPost=async(id:string,action:string)=>{setActing(id);try{await fetch("/api/admin/community/guest-posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})});toast.success(`${action}d`);window.location.reload();}catch{toast.error("Failed");}finally{setActing(null);}};
  const reviewQ=async(id:string,action:string)=>{setActing(id);try{await fetch("/api/admin/community/questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})});toast.success(`${action}d`);window.location.reload();}catch{toast.error("Failed");}finally{setActing(null);}};
  const total=stats.pendingGuestPosts+stats.pendingQuestions+stats.draftBlogPosts+stats.unpublishedExams+stats.unpublishedColleges;
  const badge=(s:string)=>s==="PENDING"?<Badge variant="outline" className="text-[10px] gap-0.5"><Clock className="h-2.5 w-2.5"/>Pending</Badge>:s==="APPROVED"||s==="PUBLISHED"?<Badge variant="secondary" className="text-[10px] gap-0.5 bg-emerald-100 text-emerald-700"><CheckCircle2 className="h-2.5 w-2.5"/>{s}</Badge>:<Badge variant="secondary" className="text-[10px] gap-0.5 bg-red-100 text-red-700"><XCircle className="h-2.5 w-2.5"/>Rejected</Badge>;
  const Empty=({t}:{t:string})=><Card className="border-dashed"><CardContent className="py-6 text-center text-sm text-muted-foreground">{t}</CardContent></Card>;
  return<div className="space-y-6">
    <div className="grid gap-3 sm:grid-cols-4"><Card><CardContent className="pt-4"><div className="text-xl font-bold text-amber-600">{total}</div><div className="text-[10px] text-muted-foreground">Pending Review</div></CardContent></Card><Card><CardContent className="pt-4"><div className="text-xl font-bold text-blue-600">{stats.totalReviews}</div><div className="text-[10px] text-muted-foreground">Reviews</div></CardContent></Card><Card><CardContent className="pt-4"><div className="text-xl font-bold text-emerald-600">{stats.totalComments}</div><div className="text-[10px] text-muted-foreground">Comments</div></CardContent></Card><Card><CardContent className="pt-4"><div className="text-xl font-bold">{stats.pendingGuestPosts+stats.pendingQuestions}</div><div className="text-[10px] text-muted-foreground">Community</div></CardContent></Card></div>
    <Tabs defaultValue="posts"><TabsList className="flex-wrap"><TabsTrigger value="posts" className="gap-1 text-xs"><FileText className="h-3.5 w-3.5"/>Posts ({stats.pendingGuestPosts})</TabsTrigger><TabsTrigger value="questions" className="gap-1 text-xs"><HelpCircle className="h-3.5 w-3.5"/>Questions ({stats.pendingQuestions})</TabsTrigger><TabsTrigger value="drafts" className="gap-1 text-xs"><Newspaper className="h-3.5 w-3.5"/>Drafts ({stats.draftBlogPosts})</TabsTrigger><TabsTrigger value="unpub" className="gap-1 text-xs"><Clock className="h-3.5 w-3.5"/>Unpublished ({stats.unpublishedExams+stats.unpublishedColleges})</TabsTrigger></TabsList>
      <TabsContent value="posts" className="mt-4 space-y-2">{guestPosts.length===0?<Empty t="No pending posts."/>:guestPosts.map(p=><Card key={p.id}><CardContent className="py-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex items-center gap-2 mb-1"><span className="font-medium text-sm">{p.title}</span>{badge("PENDING")}</div><p className="text-xs text-muted-foreground">By {p.authorName} · {new Date(p.createdAt).toLocaleDateString()}</p><p className="text-xs text-muted-foreground mt-1 line-clamp-2">{p.excerpt}</p></div><div className="flex flex-col gap-1 shrink-0"><Button size="sm" variant="outline" onClick={()=>reviewPost(p.id,"approve")} disabled={acting===p.id}>Approve</Button><Button size="sm" onClick={()=>reviewPost(p.id,"publish")} disabled={acting===p.id}>Publish</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={()=>reviewPost(p.id,"reject")} disabled={acting===p.id}>Reject</Button></div></div></CardContent></Card>)}</TabsContent>
      <TabsContent value="questions" className="mt-4 space-y-2">{questions.length===0?<Empty t="No pending questions."/>:questions.map(q=><Card key={q.id}><CardContent className="py-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex items-center gap-2 mb-1"><span className="font-medium text-sm">{q.question}</span>{badge("PENDING")}</div><p className="text-xs text-muted-foreground">By {q.submitterName} · {q.examTitle??"General"}</p><div className="mt-1 grid grid-cols-2 gap-1 text-xs">{["A","B","C","D"].map((l,i)=><div key={l} className={cn("flex items-center gap-1 rounded p-1",q.correctAnswer===l?"bg-emerald-50 text-emerald-700 font-medium":"bg-muted")}><b>{l}.</b>{[q.optionA,q.optionB,q.optionC,q.optionD][i]}</div>)}</div></div><div className="flex flex-col gap-1 shrink-0"><Button size="sm" variant="outline" onClick={()=>reviewQ(q.id,"approve")} disabled={acting===q.id}>Approve</Button><Button size="sm" onClick={()=>reviewQ(q.id,"import")} disabled={acting===q.id}>{acting===q.id?<Loader2 className="h-3 w-3 animate-spin"/>:<><Upload className="h-3 w-3 mr-1"/>Import</>}</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={()=>reviewQ(q.id,"reject")} disabled={acting===q.id}>Reject</Button></div></div></CardContent></Card>)}</TabsContent>
      <TabsContent value="drafts" className="mt-4 space-y-2">{draftPosts.length===0?<Empty t="No drafts."/>:draftPosts.map(p=><Card key={p.id}><CardContent className="py-3"><div className="flex items-start justify-between gap-3"><div><span className="font-medium text-sm">{p.title}</span><Badge variant="outline" className="ml-2 text-[10px]">DRAFT</Badge><p className="text-xs text-muted-foreground mt-1">By {p.authorName} · {p.categoryName??"Uncategorized"}</p></div><Button size="sm" variant="outline" asChild><a href={`/admin/blog/${p.id}`}><Eye className="h-3.5 w-3.5 mr-1"/>Edit</a></Button></div></CardContent></Card>)}</TabsContent>
      <TabsContent value="unpub" className="mt-4 space-y-3">{unpublishedExams.length===0&&unpublishedColleges.length===0?<Empty t="Nothing unpublished."/>:<>{unpublishedExams.length>0&&<div><h3 className="text-xs font-semibold mb-1">Exams</h3>{unpublishedExams.map(e=><Card key={e.id}><CardContent className="py-2 flex items-center justify-between"><span className="text-sm">{e.title}</span></CardContent></Card>)}</div>}<p className="text-xs text-muted-foreground">+ {stats.unpublishedColleges} unpublished colleges.</p></>}</TabsContent>
    </Tabs>
  </div>;
}
