/**
 * Phase 2 seed: Banks, Jobs, Government Services
 * Run: `bun run scripts/seed-phase2.ts`
 */
import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

async function main() {
  console.log("🌱 Seeding Phase 2: Banks, Jobs, Government Services...");

  // ─── BANKS ──────────────────────────────────────────────────
  const banks = [
    {
      slug: "nepal-bank-limited",
      name: "Nepal Bank Limited",
      shortName: "NBL",
      description: "Nepal Bank Limited is the first commercial bank of Nepal, established in 1937. As the pioneer of banking in Nepal, it has played a crucial role in the country's economic development for over 85 years. The bank offers a wide range of banking services including retail banking, corporate banking, international trade finance, and digital banking solutions.",
      type: "COMMERCIAL", establishedYear: 1937,
      headquarters: "Kathmandu", website: "https://nepalbank.com.np",
      phone: "+977-1-4228000", email: "info@nepalbank.com.np",
      swiftCode: "NEBLNPKA",
      savingsRateMin: 2.5, savingsRateMax: 5.0,
      fixedDepositRateMin: 5.5, fixedDepositRateMax: 9.5,
      branchCount: 232, atmCount: 350,
      mobileBanking: true, internetBanking: true,
      cards: JSON.stringify(["Visa Debit", "Mastercard Credit", "Visa Credit", " rupay"]),
      loans: JSON.stringify(["Home Loan", "Auto Loan", "Personal Loan", "Education Loan", "Business Loan", "Gold Loan"]),
      rating: 4.0, reviewCount: 156, isFeatured: true,
    },
    {
      slug: "nabil-bank",
      name: "Nabil Bank Limited",
      shortName: "NABIL",
      description: "Nabil Bank is one of Nepal's leading private sector commercial banks, established in 1984. The bank has a strong presence across the country with modern banking services and innovative digital solutions. Nabil is known for its customer-centric approach and is a subsidiary of NIC Asia Group.",
      type: "COMMERCIAL", establishedYear: 1984,
      headquarters: "Kathmandu", website: "https://nabilbank.com",
      phone: "+977-1-4427444", email: "info@nabilbank.com",
      swiftCode: "NARBNPKA",
      savingsRateMin: 3.0, savingsRateMax: 6.0,
      fixedDepositRateMin: 6.0, fixedDepositRateMax: 10.0,
      branchCount: 268, atmCount: 425,
      mobileBanking: true, internetBanking: true,
      cards: JSON.stringify(["Visa Debit", "Mastercard Credit", "Visa Credit", "American Express"]),
      loans: JSON.stringify(["Home Loan", "Auto Loan", "Personal Loan", "Education Loan", "Business Loan", "Gold Loan", "Overdraft Facility"]),
      rating: 4.3, reviewCount: 189, isFeatured: true,
    },
    {
      slug: "global-ime-bank",
      name: "Global IME Bank Limited",
      shortName: "GLOBAL",
      description: "Global IME Bank is one of the largest private commercial banks in Nepal, formed through mergers with several financial institutions. The bank has the largest network of branches across all 77 districts of Nepal and serves over 3 million customers with comprehensive banking services.",
      type: "COMMERCIAL", establishedYear: 2007,
      headquarters: "Kathmandu", website: "https://globalimebank.com",
      phone: "+977-1-4444444", email: "info@globalimebank.com",
      swiftCode: "GLOBNPKA",
      savingsRateMin: 2.75, savingsRateMax: 5.5,
      fixedDepositRateMin: 5.75, fixedDepositRateMax: 9.75,
      branchCount: 355, atmCount: 480,
      mobileBanking: true, internetBanking: true,
      cards: JSON.stringify(["Visa Debit", "Mastercard Debit", "Visa Credit"]),
      loans: JSON.stringify(["Home Loan", "Auto Loan", "Personal Loan", "Education Loan", "Business Loan", "Gold Loan", "Share Loan"]),
      rating: 4.2, reviewCount: 142, isFeatured: true,
    },
    {
      slug: "nic-asia-bank",
      name: "NIC Asia Bank Limited",
      shortName: "NIC",
      description: "NIC Asia Bank is one of the largest private sector commercial banks in Nepal. The bank has been at the forefront of digital banking innovation in Nepal and offers 24/7 banking services through its digital platforms. NIC Asia is known for its modern banking approach and excellent customer service.",
      type: "COMMERCIAL", establishedYear: 1998,
      headquarters: "Kathmandu", website: "https://nicasiabank.com",
      phone: "+977-1-4411225", email: "info@nicasiabank.com",
      swiftCode: "NICANPKA",
      savingsRateMin: 3.0, savingsRateMax: 6.0,
      fixedDepositRateMin: 6.0, fixedDepositRateMax: 10.5,
      branchCount: 290, atmCount: 510,
      mobileBanking: true, internetBanking: true,
      cards: JSON.stringify(["Visa Debit", "Mastercard Debit", "Visa Credit", " rupay"]),
      loans: JSON.stringify(["Home Loan", "Auto Loan", "Personal Loan", "Education Loan", "Business Loan", "Gold Loan", "Express Loan"]),
      rating: 4.4, reviewCount: 167, isFeatured: true,
    },
    {
      slug: "everest-bank",
      name: "Everest Bank Limited",
      shortName: "EBL",
      description: "Everest Bank Limited is a leading commercial bank in Nepal with a strong presence in retail and corporate banking. The bank has a strategic partnership with Punjab National Bank of India and offers specialized services including NRI banking, trade finance, and SME lending.",
      type: "COMMERCIAL", establishedYear: 1994,
      headquarters: "Kathmandu", website: "https://everestbankltd.com",
      phone: "+977-1-4256000", email: "info@everestbankltd.com",
      swiftCode: "EVBLNPKA",
      savingsRateMin: 2.5, savingsRateMax: 5.0,
      fixedDepositRateMin: 5.5, fixedDepositRateMax: 9.5,
      branchCount: 105, atmCount: 145,
      mobileBanking: true, internetBanking: true,
      cards: JSON.stringify(["Visa Debit", "Mastercard Credit", "Visa Credit"]),
      loans: JSON.stringify(["Home Loan", "Auto Loan", "Personal Loan", "Education Loan", "Business Loan", "Gold Loan"]),
      rating: 4.1, reviewCount: 98,
    },
    {
      slug: "prabhu-bank",
      name: "Prabhu Bank Limited",
      shortName: "PRABHU",
      description: "Prabhu Bank is a national-level commercial bank in Nepal formed through the merger of several finance companies. The bank offers a comprehensive range of banking services with a focus on retail banking and remittance services for Nepali workers abroad.",
      type: "COMMERCIAL", establishedYear: 2013,
      headquarters: "Kathmandu", website: "https://prabhubank.com",
      phone: "+977-1-4444444", email: "info@prabhubank.com",
      swiftCode: "PRBUNPKA",
      savingsRateMin: 2.5, savingsRateMax: 5.5,
      fixedDepositRateMin: 5.5, fixedDepositRateMax: 9.5,
      branchCount: 288, atmCount: 320,
      mobileBanking: true, internetBanking: true,
      cards: JSON.stringify(["Visa Debit", "Mastercard Debit"]),
      loans: JSON.stringify(["Home Loan", "Auto Loan", "Personal Loan", "Education Loan", "Business Loan", "Gold Loan"]),
      rating: 3.9, reviewCount: 76,
    },
    {
      slug: "agricultural-development-bank",
      name: "Agricultural Development Bank Limited",
      shortName: "ADBL",
      description: "Agricultural Development Bank Limited (ADBL) is a government-owned commercial bank specializing in agricultural and rural development financing. Established in 2006, ADBL plays a vital role in providing credit to farmers, agribusinesses, and rural communities across Nepal.",
      type: "COMMERCIAL", establishedYear: 2006,
      headquarters: "Kathmandu", website: "https://adbl.gov.np",
      phone: "+977-1-4244000", email: "info@adbl.gov.np",
      swiftCode: "ADBLNPKA",
      savingsRateMin: 3.0, savingsRateMax: 5.5,
      fixedDepositRateMin: 5.5, fixedDepositRateMax: 9.0,
      branchCount: 250, atmCount: 220,
      mobileBanking: true, internetBanking: true,
      cards: JSON.stringify(["Visa Debit", " rupay"]),
      loans: JSON.stringify(["Agricultural Loan", "Home Loan", "Auto Loan", "Personal Loan", "Business Loan", "Tractor Loan", "Livestock Loan"]),
      rating: 3.8, reviewCount: 64,
    },
    {
      slug: "rastriya-banijya-bank",
      name: "Rastriya Banijya Bank",
      shortName: "RBB",
      description: "Rastriya Banijya Bank (RBB) is the largest commercial bank in Nepal by deposits, fully owned by the Government of Nepal. Established in 1965, RBB has the most extensive branch network in the country and serves millions of customers including government employees, businesses, and individuals.",
      type: "COMMERCIAL", establishedYear: 1965,
      headquarters: "Kathmandu", website: "https://rastriyabanijyabank.com",
      phone: "+977-1-4241111", email: "info@rbb.com.np",
      swiftCode: "RBBANPKA",
      savingsRateMin: 2.5, savingsRateMax: 5.0,
      fixedDepositRateMin: 5.0, fixedDepositRateMax: 9.0,
      branchCount: 290, atmCount: 320,
      mobileBanking: true, internetBanking: true,
      cards: JSON.stringify(["Visa Debit", " rupay"]),
      loans: JSON.stringify(["Home Loan", "Auto Loan", "Personal Loan", "Education Loan", "Business Loan", "Gold Loan", "Government Salary Loan"]),
      rating: 3.7, reviewCount: 132,
    },
  ];

  for (const b of banks) {
    await db.bank.upsert({ where: { slug: b.slug }, update: b, create: b });
  }
  console.log(`✓ ${banks.length} banks`);

  // ─── JOBS ───────────────────────────────────────────────────
  const jobs = [
    {
      slug: "junior-software-engineer-f1soft",
      title: "Junior Software Engineer",
      description: "F1Soft International is hiring Junior Software Engineers to join our engineering team. You will work on cutting-edge fintech products serving millions of users across Nepal. We offer a collaborative environment, mentorship from senior engineers, and opportunities to work with modern technologies including Java, Spring Boot, React, and AWS. Fresh graduates with strong fundamentals are encouraged to apply.",
      company: "F1Soft International",
      companyLogo: null, location: "Kathmandu, Nepal",
      jobType: "FULL_TIME", category: "IT", experienceLevel: "ENTRY",
      salaryMin: 35000, salaryMax: 55000, salaryCurrency: "NPR",
      applicationUrl: "https://f1soft.com/careers",
      applicationEmail: "careers@f1soft.com",
      deadline: new Date("2026-07-31"),
      skills: JSON.stringify(["Java", "Spring Boot", "React", "SQL", "Git", "REST API"]),
      qualifications: JSON.stringify([
        "Bachelors degree in Computer Science, Engineering or related field",
        "Strong understanding of data structures and algorithms",
        "Knowledge of at least one programming language (Java/Python/JavaScript)",
        "Familiarity with web technologies (HTML, CSS, JavaScript)",
        "Good problem-solving skills and willingness to learn",
      ]),
      views: 1240, isFeatured: true,
    },
    {
      slug: "mbbs-doctor-teaching-hospital",
      title: "Medical Officer (MBBS Doctor)",
      description: "Tribhuvan University Teaching Hospital (TUTH) is seeking qualified MBBS doctors to join as Medical Officers. The position offers an excellent opportunity to gain clinical experience in one of Nepal's premier teaching hospitals. Selected candidates will work under senior consultants, manage inpatient and outpatient cases, and participate in academic activities.",
      company: "Tribhuvan University Teaching Hospital",
      companyLogo: null, location: "Kathmandu, Nepal",
      jobType: "FULL_TIME", category: "HEALTHCARE", experienceLevel: "ENTRY",
      salaryMin: 60000, salaryMax: 85000, salaryCurrency: "NPR",
      applicationUrl: null, applicationEmail: "hr@iom.edu.np",
      deadline: new Date("2026-07-15"),
      skills: JSON.stringify(["Clinical Diagnosis", "Patient Care", "Emergency Medicine", "Medical Documentation"]),
      qualifications: JSON.stringify([
        "MBBS degree from a recognized university",
        "Registered with Nepal Medical Council (NMC)",
        "Fresh graduates or up to 2 years of experience",
        "Willingness to work in shifts including night duty",
        "Good communication skills in Nepali and English",
      ]),
      views: 980, isFeatured: true,
    },
    {
      slug: "civil-engineer-consultant",
      title: "Civil Engineer (Consultant)",
      description: "We are looking for an experienced Civil Engineer to join our consulting team for various infrastructure projects across Nepal. The candidate will be responsible for project planning, site supervision, quality control, and client coordination. Projects include residential buildings, commercial complexes, and rural infrastructure development.",
      company: "Engineering Consultancy Services Nepal",
      companyLogo: null, location: "Lalitpur, Nepal",
      jobType: "FULL_TIME", category: "ENGINEERING", experienceLevel: "MID",
      salaryMin: 55000, salaryMax: 85000, salaryCurrency: "NPR",
      applicationUrl: null, applicationEmail: "hr@ecsnepal.com",
      deadline: new Date("2026-08-15"),
      skills: JSON.stringify(["AutoCAD", "Structural Design", "Project Management", "Site Supervision", "BOQ Preparation"]),
      qualifications: JSON.stringify([
        "Bachelors degree in Civil Engineering",
        "3-5 years of relevant work experience",
        "Registered with Nepal Engineering Council",
        "Proficiency in AutoCAD and engineering software",
        "Strong project management skills",
      ]),
      views: 670, isFeatured: true,
    },
    {
      slug: "marketing-intern-daraz",
      title: "Marketing Intern",
      description: "Daraz Nepal is offering an exciting 3-month internship opportunity for marketing enthusiasts. Interns will work with the digital marketing team on campaign management, content creation, social media strategy, and analytics. High-performing interns may be offered full-time positions upon completion.",
      company: "Daraz Nepal",
      companyLogo: null, location: "Kathmandu, Nepal",
      jobType: "INTERNSHIP", category: "MARKETING", experienceLevel: "ENTRY",
      salaryMin: 15000, salaryMax: 20000, salaryCurrency: "NPR",
      applicationUrl: "https://daraz.com.np/careers",
      applicationEmail: null,
      deadline: new Date("2026-07-10"),
      skills: JSON.stringify(["Digital Marketing", "Social Media", "Content Writing", "Canva", "Google Analytics"]),
      qualifications: JSON.stringify([
        "Currently enrolled in Bachelors or Masters program (Marketing/Business)",
        "Strong written and verbal communication skills",
        "Familiarity with social media platforms",
        "Creative mindset and eagerness to learn",
        "Available for full-time internship (6 days a week)",
      ]),
      views: 1450, isFeatured: true,
    },
    {
      slug: "banking-officer-nabil",
      title: "Banking Officer (Customer Service)",
      description: "Nabil Bank is hiring Banking Officers for various branches across Nepal. The role involves customer service, account opening, transaction processing, cross-selling bank products, and branch operations. Nabil offers excellent career growth opportunities and comprehensive training programs.",
      company: "Nabil Bank Limited",
      companyLogo: null, location: "Multiple Locations, Nepal",
      jobType: "FULL_TIME", category: "FINANCE", experienceLevel: "ENTRY",
      salaryMin: 35000, salaryMax: 45000, salaryCurrency: "NPR",
      applicationUrl: "https://nabilbank.com/careers",
      applicationEmail: null,
      deadline: new Date("2026-07-25"),
      skills: JSON.stringify(["Customer Service", "Banking Operations", "Cash Handling", "MS Office", "Communication"]),
      qualifications: JSON.stringify([
        "Bachelors degree in Management, Business Studies or related field",
        "Minimum 2nd division or CGPA 2.5",
        "Age not exceeding 28 years",
        "Good interpersonal and communication skills",
        "Computer literate with MS Office proficiency",
      ]),
      views: 2100, isFeatured: true,
    },
    {
      slug: "chartered-accountant-trainee",
      title: "Chartered Accountant Trainee (Articleship)",
      description: "Leading CA firm in Kathmandu is offering articleship opportunities for aspiring Chartered Accountants. The trainees will work on audit assignments, tax planning, financial reporting, and advisory services for clients across various industries. This is an excellent opportunity to build a career in professional accounting.",
      company: "B.R. Sharma & Associates",
      companyLogo: null, location: "Kathmandu, Nepal",
      jobType: "FULL_TIME", category: "FINANCE", experienceLevel: "ENTRY",
      salaryMin: 12000, salaryMax: 18000, salaryCurrency: "NPR",
      applicationUrl: null, applicationEmail: "info@brsharma.com.np",
      deadline: new Date("2026-08-31"),
      skills: JSON.stringify(["Accounting", "Auditing", "Taxation", "Tally", "Excel"]),
      qualifications: JSON.stringify([
        "Completed CAP-II or equivalent from ICAN",
        "Bachelors degree in Commerce/Management preferred",
        "Strong foundation in accounting principles",
        "Willingness to pursue CA for 3 years",
        "Good analytical and numerical skills",
      ]),
      views: 890,
    },
    {
      slug: "english-teacher-secondary",
      title: "Secondary Level English Teacher",
      description: "Reputed secondary school in Kathmandu is seeking a qualified English teacher for Grades 9-10 (SEE level). The candidate should be passionate about teaching, capable of creating engaging lesson plans, and committed to student development. We offer a competitive salary and a supportive work environment.",
      company: "Kathmandu Model Secondary School",
      companyLogo: null, location: "Kathmandu, Nepal",
      jobType: "FULL_TIME", category: "EDUCATION", experienceLevel: "MID",
      salaryMin: 30000, salaryMax: 45000, salaryCurrency: "NPR",
      applicationUrl: null, applicationEmail: "info@kmss.edu.np",
      deadline: new Date("2026-07-20"),
      skills: JSON.stringify(["English Literature", "Lesson Planning", "Classroom Management", "Curriculum Development"]),
      qualifications: JSON.stringify([
        "Masters degree in English or related field",
        "B.Ed. or equivalent teaching qualification",
        "Minimum 2 years of teaching experience at secondary level",
        "Registered with Teacher Service Commission (preferred)",
        "Excellent communication skills in English",
      ]),
      views: 560,
    },
    {
      slug: "react-developer-remote",
      title: "Senior React Developer (Remote)",
      description: "International SaaS company is hiring a Senior React Developer to work remotely from Nepal. You will lead frontend development for our flagship product, mentor junior developers, and collaborate with cross-functional teams. We offer competitive USD salary, flexible working hours, and modern tech stack.",
      company: "CloudTech Solutions",
      companyLogo: null, location: "Remote (Nepal)",
      jobType: "REMOTE", category: "IT", experienceLevel: "SENIOR",
      salaryMin: 150000, salaryMax: 250000, salaryCurrency: "NPR",
      applicationUrl: "https://cloudtech.com/careers",
      applicationEmail: null,
      deadline: new Date("2026-08-10"),
      skills: JSON.stringify(["React", "TypeScript", "Next.js", "Redux", "GraphQL", "AWS", "CI/CD"]),
      qualifications: JSON.stringify([
        "5+ years of professional frontend development experience",
        "Expert-level proficiency in React and TypeScript",
        "Experience with Next.js and modern React patterns",
        "Strong understanding of state management (Redux, Zustand)",
        "Experience leading projects and mentoring developers",
        "Excellent English communication skills",
      ]),
      views: 1850, isFeatured: true,
    },
  ];

  for (const j of jobs) {
    await db.job.upsert({ where: { slug: j.slug }, update: j, create: j });
  }
  console.log(`✓ ${jobs.length} jobs`);

  // ─── GOVERNMENT SERVICES ────────────────────────────────────
  const govtServices = [
    {
      slug: "nepali-citizenship-certificate",
      title: "Nepali Citizenship Certificate (Nagarikta)",
      description: "The Nepali Citizenship Certificate (Nagarikta) is the primary identity document for Nepali citizens. It is required for almost all official purposes including opening bank accounts, getting a passport, registering for exams, buying property, and more. This guide covers the process of obtaining a citizenship certificate by descent, naturalization, and other categories.",
      category: "CITIZENSHIP",
      ministry: "Ministry of Home Affairs",
      department: "Department of Citizenship",
      office: "District Administration Office",
      applicationUrl: "https://moha.gov.np",
      applicationFee: "Free (by descent) / NPR 5,000 (naturalization)",
      processingTime: "1-30 days depending on category",
      requiredDocuments: JSON.stringify([
        "Citizenship certificate of father/mother (for descent)",
        "Birth certificate or school leaving certificate",
        "Marriage certificate (if applying after marriage)",
        "Land ownership certificate (Lalpurja) or rental agreement",
        "2 passport-size photographs",
        "Recommendation letter from local ward office",
        "Old citizenship (if replacing/correcting)",
      ]),
      steps: JSON.stringify([
        "Visit your local Ward Office to get a recommendation letter",
        "Collect all required documents and make photocopies",
        "Visit the District Administration Office (DAO) with original documents",
        "Submit the application form along with documents and photographs",
        "Verification by the Chief District Officer (CDO) or designated officer",
        "Interview/verification of recommendation letters",
        "Citizenship certificate printed and issued (usually same day or within a week)",
      ]),
      contactPhone: "+977-1-4423000", contactEmail: "info@moha.gov.np",
      views: 25400, isFeatured: true,
    },
    {
      slug: "nepali-passport-application",
      title: "Nepali Passport (MRP) Application",
      description: "The Nepali passport is the official travel document issued to Nepali citizens for international travel. The Department of Passports issues Machine Readable Passports (MRP) and e-Passports. This guide covers the online application process, document requirements, fees, and appointment booking for passport application in Nepal.",
      category: "PASSPORT",
      ministry: "Ministry of Foreign Affairs",
      department: "Department of Passports",
      office: "Department of Passports, Narayanhiti, Kathmandu",
      applicationUrl: "https://nepalpassport.gov.np",
      applicationFee: "NPR 5,000 (normal 30 days) / NPR 7,000 (urgent 7 days) / NPR 10,000 (very urgent 3 days)",
      processingTime: "3-30 days depending on fee tier",
      requiredDocuments: JSON.stringify([
        "Original Nepali citizenship certificate",
        "Old passport (if renewing)",
        "Online application form printout with barcode",
        "Appointment confirmation receipt",
        "Birth certificate (for minors under 16)",
        "Marriage certificate (if name changed after marriage)",
        "Photograph taken at the passport office",
      ]),
      steps: JSON.stringify([
        "Visit nepalpassport.gov.np and create an account",
        "Fill out the online application form with personal details",
        "Upload required documents (citizenship, photo)",
        "Choose service type (Normal/Urgent/Very Urgent) and pay fee at designated bank",
        "Book an appointment date for biometric enrollment",
        "Visit the passport office on appointment date with original documents",
        "Biometric enrollment (fingerprints, photograph, signature)",
        "Collect passport on the specified date or opt for courier delivery",
      ]),
      contactPhone: "+977-1-4440208", contactEmail: "info@nepalpassport.gov.np",
      views: 31200, isFeatured: true,
    },
    {
      slug: "pan-registration",
      title: "PAN (Permanent Account Number) Registration",
      description: "PAN (Permanent Account Number) is a 9-digit unique identification number issued by the Inland Revenue Department (IRD) of Nepal. PAN is mandatory for filing income tax, conducting business transactions above NPR 50,000, opening bank accounts, and registering vehicles. Both individuals and businesses can apply for PAN.",
      category: "PAN",
      ministry: "Ministry of Finance",
      department: "Inland Revenue Department (IRD)",
      office: "Inland Revenue Office (nearest to your business/residence)",
      applicationUrl: "https://ird.gov.np",
      applicationFee: "Free",
      processingTime: "Same day (online) / 1-3 days (offline)",
      requiredDocuments: JSON.stringify([
        "Nepali citizenship certificate (for individuals)",
        "Company registration certificate (for businesses)",
        "PAN application form (filled online or offline)",
        "Recent passport-size photograph",
        "Business address proof (rental agreement or ownership)",
        "Memorandum of Association (for companies)",
        "PAN of directors (for company PAN application)",
      ]),
      steps: JSON.stringify([
        "Visit ird.gov.np and click on 'Online PAN Registration'",
        "Choose PAN type: Individual or Business/Entity",
        "Fill in personal details, address, and contact information",
        "Upload required documents (citizenship, photo, business docs)",
        "Submit the application online",
        "Visit the IRD office for verification (if required)",
        "Receive PAN certificate immediately online or collect from IRD office",
      ]),
      contactPhone: "+977-1-4417344", contactEmail: "info@ird.gov.np",
      views: 18900, isFeatured: true,
    },
    {
      slug: "driving-license-new-application",
      title: "Driving License — New Application",
      description: "Driving license is an official document issued by the Department of Transport Management (DoTM) that authorizes an individual to operate a motor vehicle in Nepal. This guide covers the complete process of applying for a new driving license including online application, written exam, trial test, and license collection.",
      category: "LICENSE",
      ministry: "Ministry of Physical Infrastructure and Transport",
      department: "Department of Transport Management (DoTM)",
      office: "Transport Management Office (your district)",
      applicationUrl: "https://dotm.gov.np",
      applicationFee: "NPR 1,000 (Category A) - NPR 1,500 (Category B) + NPR 500 (smart card)",
      processingTime: "1-3 months (depending on exam dates and trial pass)",
      requiredDocuments: JSON.stringify([
        "Nepali citizenship certificate (original + copy)",
        "Blood group card or medical certificate",
        "Online application form printout",
        "Fee deposit voucher from designated bank",
        "2 passport-size photographs",
        "Medical fitness certificate (for heavy vehicles)",
      ]),
      steps: JSON.stringify([
        "Visit dotm.gov.np and create an account",
        "Fill out the online application form",
        "Upload citizenship and photograph",
        "Choose category (A, B, C, D, K) and select exam office",
        "Pay application fee at designated bank",
        "Get written exam date (usually within 1 month)",
        "Pass written exam (60% passing marks)",
        "Get trial test date (usually within 2 weeks of written exam)",
        "Pass trial test (8-track, gradient, garage parking)",
        "Submit biometrics and receive smart card license (1-2 weeks after trial pass)",
      ]),
      contactPhone: "+977-1-4211008", contactEmail: "info@dotm.gov.np",
      views: 42300, isFeatured: true,
    },
    {
      slug: "vat-registration",
      title: "VAT (Value Added Tax) Registration",
      description: "VAT (Value Added Tax) registration is mandatory for businesses in Nepal with annual turnover exceeding NPR 5 million. VAT is a multi-stage tax levied on the value added at each stage of production and distribution. This guide covers the VAT registration process, documents required, and compliance requirements for businesses in Nepal.",
      category: "TAX",
      ministry: "Ministry of Finance",
      department: "Inland Revenue Department (IRD)",
      office: "Inland Revenue Office (where your PAN is registered)",
      applicationUrl: "https://ird.gov.np",
      applicationFee: "Free",
      processingTime: "15-30 days",
      requiredDocuments: JSON.stringify([
        "PAN certificate",
        "Company/firm registration certificate",
        "Citizenship certificate of proprietor/director",
        "Memorandum & Articles of Association (for companies)",
        "Business premises rental agreement or ownership document",
        "Recent photograph of proprietor/director",
        "VAT registration application form",
        "Bank account details",
      ]),
      steps: JSON.stringify([
        "Ensure your business has PAN registration",
        "Gather all required documents",
        "Visit IRD office or apply online through ird.gov.np",
        "Submit VAT registration application with documents",
        "IRD officer conducts site inspection of business premises",
        "Verification of documents and business activities",
        "Approval and issuance of VAT registration certificate",
        "Receive VAT TIN number (separate from PAN)",
        "Start filing monthly VAT returns from next tax period",
      ]),
      contactPhone: "+977-1-4417344", contactEmail: "info@ird.gov.np",
      views: 7800,
    },
    {
      slug: "land-registration-maujuda",
      title: "Land Registration (Maujuda Khani/Registration)",
      description: "Land registration (Maujuda Khani) is the process of officially registering land ownership in the name of the buyer at the Malpot Office (Land Revenue Office). This is the final and most critical step in any land/property transaction in Nepal. The process transfers legal ownership rights from the seller to the buyer.",
      category: "LAND",
      ministry: "Ministry of Land Management, Cooperatives and Poverty Alleviation",
      department: "Department of Land Management and Archives",
      office: "Malpot Office (Land Revenue Office) of the district where land is located",
      applicationUrl: "https://malpot.gov.np",
      applicationFee: "4-5% of property value (capital gains tax + registration fee)",
      processingTime: "1-3 days",
      requiredDocuments: JSON.stringify([
        "Original land ownership certificate (Lalpurja) of seller",
        "Sale deed (Rajinama) — executed on stamp paper",
        "Citizenship certificates of buyer and seller",
        "Recent land revenue receipt (Tiro tiraune rasid)",
        "Boundary verification letter from survey office",
        "4 photographs each of buyer and seller",
        "Tax clearance certificate (if applicable)",
        "Power of attorney (if represented by someone else)",
      ]),
      steps: JSON.stringify([
        "Draft and execute sale deed (Rajinama) on stamp paper with witnesses",
        "Conduct land boundary verification at the local survey office",
        "Pay capital gains tax at IRD office (calculated on profit)",
        "Visit Malpot Office with all documents and both parties",
        "Submit sale deed, lalpurja, citizenship, and tax receipts",
        "Pay registration fee (4-5% of property valuation by Malpot)",
        "Malpot officer verifies documents and ownership history",
        "New Lalpurja printed in the name of buyer",
        "Update land records in the official registry",
      ]),
      contactPhone: "+977-1-4211000", contactEmail: "info@malpot.gov.np",
      views: 11200,
    },
    {
      slug: "vehicle-registration-bahidar",
      title: "Vehicle Registration (Bahi Daftar)",
      description: "Vehicle registration (Bahi Daftar) is the process of officially registering a new or used vehicle with the Transport Management Office. All motor vehicles in Nepal must be registered within 30 days of purchase. The registration provides the vehicle with a unique bluebook (registration certificate) and number plate.",
      category: "VEHICLE",
      ministry: "Ministry of Physical Infrastructure and Transport",
      department: "Department of Transport Management (DoTM)",
      office: "Transport Management Office (your province/district)",
      applicationUrl: "https://dotm.gov.np",
      applicationFee: "Varies by vehicle type (NPR 1,000 - NPR 10,000+)",
      processingTime: "1-3 days",
      requiredDocuments: JSON.stringify([
        "Nepali citizenship certificate of owner",
        "Vehicle invoice/bill of sale",
        "Customs clearance certificate (for imported vehicles)",
        "Manufacturer's certificate of Origin",
        "Insurance certificate",
        "PAN of dealer (if purchased from dealer)",
        "Vehicle inspection report",
        "Application form for vehicle registration",
      ]),
      steps: JSON.stringify([
        "Purchase vehicle and obtain invoice and customs documents",
        "Insure the vehicle at an authorized insurance company",
        "Visit the Transport Management Office with vehicle and documents",
        "Submit application form with all required documents",
        "Pay registration fee, road tax, and pollution control fee",
        "Vehicle inspection by transport officer",
        "Get bluebook (registration certificate) and number plate",
        "Install number plate on the vehicle",
        "Renew registration annually",
      ]),
      contactPhone: "+977-1-4211008", contactEmail: "info@dotm.gov.np",
      views: 9500,
    },
    {
      slug: "marriage-registration",
      title: "Marriage Registration Certificate",
      description: "The marriage registration certificate is the official document proving the legal union between two individuals in Nepal. Marriage registration is mandatory for various purposes including visa applications, opening joint bank accounts, claiming insurance benefits, and changing name after marriage. Both court marriages and traditional marriages can be registered.",
      category: "OTHER",
      ministry: "Ministry of Federal Affairs and General Administration",
      department: "Department of Civil Registration",
      office: "Local Ward Office or District Administration Office",
      applicationUrl: null,
      applicationFee: "NPR 200 - NPR 500",
      processingTime: "1-7 days",
      requiredDocuments: JSON.stringify([
        "Citizenship certificates of both bride and groom",
        "Birth certificates of both parties",
        "Photographs of marriage ceremony",
        "Invitation card of marriage",
        "Recommendation letter from local ward office",
        "Statement from witness (with citizenship)",
        "For court marriage: affidavit and medical certificate",
        "If previously married: divorce decree or death certificate of spouse",
      ]),
      steps: JSON.stringify([
        "Collect recommendation letter from local ward office",
        "Gather all required documents with photocopies",
        "Visit the District Administration Office or local ward office",
        "Submit marriage registration application with documents",
        "Pay the registration fee",
        "Verification by the registration officer",
        "Marriage certificate issued (usually same day or within a week)",
      ]),
      contactPhone: "+977-1-4211000", contactEmail: null,
      views: 6700,
    },
  ];

  for (const g of govtServices) {
    await db.governmentService.upsert({ where: { slug: g.slug }, update: g, create: g });
  }
  console.log(`✓ ${govtServices.length} government services`);

  console.log("\n🎉 Phase 2 seeding completed!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
